const data = [
  {
    id: 1,
    img: "https://i.ibb.co/0QbcYBS/Aire-acondicionado-Split-Kanji-2600w-f-c-26fkht81.jpg",
    title: "Aire Acondicionado Split KANJI 2600w FC",
    price: "$00.00",
    category: "aire",
    marca: "KANJI",
    modelo: "26FKHT81",
    deflectoresmoviles: "Sí",
    frigorias: "2240",
    display: "No",
    timer: "Sí",
    automatico: "Si",
    sleep: "Sí",
    ventilacion: "Sí",
    frio_calor: "Sí",
    tipo_equipo: "Split",
    tipo_energia: "A",
    contro: "Sí",
    inverter: "No",
    gas: "R-410a",
  },
  {
    id: 2,
    img: "https://i.ibb.co/pKCPbxc/aire-acondicionado-split-hitachi-2600w-fc.jpg",
    title: "Aire Acondicionado Split HITACHI 2600w FC",
    price: "$00,00",
    category: "aire",
    marca: "HITACHI",
    tipo_equipo: "Split",
    frio_calor: "Sí",
    frigorias: "2499",
    gas: "R410A",
    tipo_energia: "A",
    automático: "Sí",
    deshumificación: "Sí",
    sleep: "Sí",
    medidasSplit: "27,5cm Alto - 85cm Ancho - 32cm Prof.",
    peso: "11 kg",
    medidasMotor: "54,5cm Alto - 70cm Ancho - 30cm Prof.",
    pesoMotor: "27 kg",
    control: "Sí",
  },

  {
    id: 3,
    img: "https://i.ibb.co/g9mKHqb/aire-acondicionado-split-kanji-3200w-fc.jpg",
    title: "Aire acondicionado Split KANJI 3200w FC",
    price: "$00,00",
    category: "aire",
    marca: "KANJI",
    display: "No",
    deflectores_moviles: "Sí",
    frigorias: "2760",
    timer: "Sí",
    automatico: "Sí",
    sleep: "Sí",
    ventilación: "Sí",
    frio_calor: "Sí",
    tipo_equipo: "Split",
    tipo_energia: "A",
    control: "Sí",
    inverter: "No",
    gas: "R-410a",
  },
  {
    id: 4,
    img: "https://i.ibb.co/r67MbZ3/aire-acondicionado-inverter-greenstay-fc-3500.jpg",
    title: "Aire acondicionado Inverter GREENSTAY 3500w FC",
    price: "$00,00",
    category: "aire",
    marca: "GREENSTAY",
    frigorias: "3010",
    tipo_equipo: "Split Inverter",
    frío_calor: "Si",
    tipo_energia: "A+",
    gas: "R-410A",
    detail:
      "Aire acondicionado Split. Tecnologia Inverter. Frigorias 3010. Potencia 3500. Control remoto. Display digital. Timer. Funcion sleep. Eficiencia energetica A. Tipo de gas refrigerante R410. Medidas unidad interior (alt-anch-prof) 29.5 x 80.2 x 20cm. Medidas unidad exterior (alt-anch-prof) 49.5 x 72 x 27cm.",
  },
  {
    id: 5,
    img: "https://i.ibb.co/HHG7r1D/aire-acondicionado-inverter-greenstay-fc-6900.jpg",
    title: "Aire acondicionado Inverter GREENSTAY 6900w FC",
    price: "$00,00",
    category: "aire",
    marca: "GREENSTAY",
    frigorias: "5934",
    tipo_equipo: "Split Inverter",
    frío_calor: "Si",
    tipo_energia: "A+",
    gas: "R-410A",
  },
  {
    id: 6,
    img: "https://i.ibb.co/TLkWf51/ventilador-vitta-18pulgadas-3-en-1-90w.jpg",
    title: "Ventilador VITTA 18'' 3 en 1 90w",
    price: "$00,00",
    category: "ventilacion",
    marca: "VITTA",
    dimensiones: "46cm",
    tipo_ventilador: "Mesa, Pared, Pie",
    potencia: "90 w",
    velocidades: "3",
    aspas: "Metal",
    cantidad_aspas: "3",
  },
  {
    id: 7,
    img: "https://i.ibb.co/7V2dS40/ventilador-industrial-vitta-30-Pulgadas-2-en-1.jpg",
    title: "Ventilador Industrial Vitta 30'' 2 en 1",
    price: "$00,00",
    category: "ventilacion",
    marca: "VITTA",
    tipo_ventilador: "Pared, Pie",
    cantidad_aspas: "3",
    velocidades: "3",
    altura: "1,4 metros",
    potencia: "180W",
    aspas: "Plásticas",
  },

  {
    id: 8,

    img: "https://i.ibb.co/N6LrtJg/Ventilador-18-Pulgadas-3-en-1-STAR-TRAK.jpg",
    title: "Ventilador 18'' 3 en 1 STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Pared, Turbo, Pie",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Metal",
    potencia: "90W",
  },
  {
    id: 9,
    img: "https://i.ibb.co/MgJGJFf/Ventilador-Pie-14-Pulgadas-Base-Pesada-STAR-TRAK.jpghttps://picsum.photos/200/300?random=9",
    title: "Ventilador Pie 14'' Base Pesada STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Fijo",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,50 metros",
    potencia: "90W",
    otro: "Repele Mosquitos",
  },
  {
    id: 10,
    img: "https://i.ibb.co/WBR7xrp/Ventilador-Pie-14-Pulgadas-STAR-TRAK-Multi.jpg",
    title: "Ventilador Pie 14'' STAR TRAK Multi",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Pared, Turbo, Pie",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,50 metros",
    potencia: "90W",
    otro: "Repele Mosquitos",
  },
  {
    id: 11,
    img: "https://i.ibb.co/kcJYp06/Ventilador-14-Pulgadas-STAR-TRAK.jpg",
    title: "Ventilador 20'' STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Fijo",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,70 Metros",
    potencia: "120W",
    otro: "Repele Mosquitos",
  },
  {
    id: 12,
    img: "https://i.ibb.co/bdQqNYr/Climatizador-Philco-Portatil-7-L.jpg",
    title: "Climatizador Philco Portatil 7L",
    price: "$00,00",
    category: "calefaccion",
    marca: "PHILCO",
    velocidades: "3",
    tipo_equipo: "Oscilación",
    otro: "No requiere instalación",
    flujo_aire: "600 m3/h",
    cantidad_agua: "7 Lts (5 Lts con los cubos de hielo reutilizables)",
    detalles: "Indicador de nivel de agua",
    timer: "No",
    peso: "6,6 kgs",
    dimesion: "Alto: 70 cm Ancho: 28 cm Prof: 26,5 cm",
  },
  {
    id: 13,
    img: "https://i.ibb.co/B2h9Vv3/Climatizador-Kanji-LRG04-11-CR-Frio-Calor.jpg",
    title: "Climatizador Kanji LRG04-11CR Frio Calor",
    price: "$00,00",
    category: "calefaccion",
    marca: "KANJI",
    velocidades: "3",
    frio_calor: "Si",
    control: "Si",
    cantidad_agua: "8 Litros",
    dimensiones: "Alto 70 cm Ancho 37 cm Prof: 29 cm",
  },
  {
    id: 14,
    img: "https://i.ibb.co/nL5qRNX/Heladera-Briket-322-L-BK2-F-1610-Blanca-Gris-Negro.jpg",
    title: "Heladera Briket 322L BK2F 1610 Blanca-Gris-Negro",
    price: "$00,00",
    category: "heladera",
    marca: "BRIKET",
    modelo: "BK2F 1610",
    color: "Blanco, Gris o Negro",
    freezer: "Superior",
    estantes_freezer: "1",
    dimensiones: "Ancho: 66cm Altura: 164cm Prof: 682cm",
    estantes_heladera: "3",
    dispenser_agua: "No",
    dispenser_hielo: "No",
    luz_interior: "Si",
    cantidad_puertas: "2",
    inverter: "No",
    tipo_energia: "A+",
    capacidad: "322 Litros",
    congelador: "No",
    vegetales: "Si",
    porta_botellas: "No",
    porta_latas: "No",
    porta_huevos: "Si",
  },
  {
    id: 15,
    img: "https://i.ibb.co/F0wyRpN/Heladera-Briket-476-L-BK2-F-2121-Gris.jpg",
    title: "Heladera Briket 476L BK2F 2121 Gris",
    price: "$00,00",
    category: "heladera",
    marca: "BRIKET",
    Modelo: "BK2F 2121",
    dimensiones: "Ancho: 66cm x Prof: 75cm x Alto: 189 cm",
    inverter: "No",
    tipo_energia: "A+",
    deshielo: "Manual",
    freezer: "Superior",
    luz_interior: "Sí",
    puertas: "2",
  },
  {
    id: 16,
    img: "https://i.ibb.co/1X2pcjr/Heladera-SIAM-Top-Mount-370l-C-Disp-inox.jpg",
    title: "Heladera SIAM Top Mount 370l C-Disp inox",
    price: "$00,00",
    category: "heladera",
    marca: "SIAM",
    modelo: "HSI-NT30XD",
    estilo: "Acero inoxidable",
    freezer: "Superior",
    estantes_freezer: "1",
    fabrica_hielo: "Si",
    peso: "68 Kg",
    dimensiones: "Ancho: 69.6cm Prof: 68.5cm Alto: 171.2cm",
    estantes_heladera: "3",
    dispenser_agua: "Si",
    dispenser_hielo: "Si",
    luz_interior: "Si",
    inverter: "Si",
    deshielo: "No Frost",
    tipo_energia: "A",
    capacidad: "404 Litros",
    niveles_temperatura: "6",
    porta_vegetales: "Si",
    cantidad_puertas: "2",
    display: "No",
  },
  {
    id: 17,
    img: "https://i.ibb.co/d4rRygF/Heladera-Samsung-Inox-321-L-con-display-RT32-K5930-SL.jpg",
    title: "Heladera Samsung Inox 321L con display RT32K5930SL",
    price: "$00,00",
    category: "heladera",
    marca: "SAMSUNG",
    modelo: "Rt32k5930sl",
    inverter: "Si",
    dimensiones: "Ancho: 60cm, Prof.: 67.2cm Alto: 171.5cm",
    luz_interior: "Si",
    tipo_energia: "A+",
    enfriamiento: "No Frost",
    cantidad_puertas: "2",
    estantes_regulables: "Si",
    porta_vegetales: "Si",
    capacidad: "320 Litros",
    capacidad_freezer: "72 Litros",
    porta_botellas: "No",
    display: "Si",
    fabrica_hielo: "Si",
    dispenser_agua: "Si",
  },
  {
    id: 18,
    img: "https://i.ibb.co/rMyxDZq/Heladera-Samsung-Inox-380-L-Con-Display-RT38-K5932-SL.jpg",
    title: "Heladera Samsung Inox 380L Con Display RT38K5932SL",
    price: "$00,00",
    category: "heladera",
    marca: "SAMSUNG",
    modelo: "RT38K5982SL/B3",
    capacidad: "394 L",
    inverter: "Sí",
    tipo_energia: "A+",
    deshielo: "No frost",
    freezer: "Superior",
    estantes_freezer: "1",
    fabrica_hielo: "Si",
    peso: "72 KG",
    dimensiones: "Ancho: 67.5cm Prof.: 66.8cm Alto: 178.5cm",
    niveles_temperatura: "5",
    porta_vegetales: "Si",
    porta_huevos: "Si",
    puertas: "2",
    display: "Si",
    sistema_air_flow: "Si",
    filtro_desodorizador: "Si",
  },
  {
    id: 19,
    img: "https://i.ibb.co/BBvMzwk/Heladera-Philco-Inox-530l-94phsb530xt.jpg",
    title: "Heladera Philco Inox 530l 94phsb530xt",
    price: "$00,00",
    category: "heladera",
    marca: "PHILCO",
    modelo: "PHSB530XT",
    capacidad: "282 L",
    inverter: "No",
    tipo_energia: "A+",
    capacidad_freezer: "218 L",
    deshielo: "No frost",
    freezer: "Side by side",
    estantes_freezer: "2",
    fabrica_hielo: "No",
    peso: "99 Kg",
    dimensiones: "Ancho: 89,5cm Prof.: 74,5cm Alto: 178,8cm",
    porta_vegetales: "Sí",
    puertas: "2",
    display: "Sí",
    sistema_air_flow: "Sí",
  },
  {
    id: 20,
    img: "https://i.ibb.co/R0xKjJ0/Heladera-BRIKET-Bajo-Mesada.jpg",
    title: "Heladera BRIKET Bajo Mesada Colores",
    price: "$00,00",
    category: "heladera",
    marca: "BRIKET",
    dimensiones: "Ancho: 55cm, Prof.: 62cm Alto: 85cm",
    peso: "3 Kg",
    capacidad: "146 Litros",
    tipo_energia: "A",
    porta_latas: "No",
    fabrica_hielo: "No",
    dispenser: "No",
    porta_vegetales: "Si",
  },
  {
    id: 21,
    img: "https://i.ibb.co/g6p4V0H/Freezer-Horizontal-Briket-FR-2500-st.jpg",
    title: "Freezer Horizontal Briket FR 2500 st",
    price: "$00,00",
    category: "freezer",
    marca: "BRIKET",
    modelo: "FR 2500",
    capacidad: "224 L",
    ruedas: "Si",
    funciones: "Enfriar, Freezar",
    tipo_energia: "B",
    peso: "50.1 Kg",
    dimensiones: "Ancho: 94,5cm Prof.: 70cm Ancho: 84cm",
    orientacion: "Horizontal",
    cantidad_puertas: "1",
  },
  {
    id: 22,
    img: "https://picsum.photos/200/300?random=10",
    title: "Freezer Horizontal Briket FR 3300 ST",
    price: "$00,00",
    category: "freezer",
    marca: "BRIKET",
    modelo: "FT 3300 ST",
    capacidad: "295 Litros",
    peso: "40 KG",
    dimensiones: "Alto: 84cm Prof.: 70cm Ancho: 115,5cm",
    orientacion: "Horizontal",
    cantidad_puertas: "1",
    cestos_deslizables: "Si",
    enfriador_botellas: "Si",
  },
  {
    id: 23,
    img: "https://i.ibb.co/8P8xJ2t/Freezer-Horizontal-Briket-FR-4500-ST-2-Puertas.jpg",
    title: "Freezer Horizontal Briket FR 4500 ST 2 Puertas",
    price: "$00,00",
    category: "freezer",
    marca: "BRIKET",
    modelo: "FR 4500",
    capacidad: "390 L",
    ruedas: "Sí",
    funciones: "Congelar, Conservar, Enfriar",
    tipo_energia: "A",
    peso: "64.4 KG",
    dimensiones: "Ancho: 148cm Prof.: 70cm Alto: 84cm",
    orientacion: "Horizontal",
    cantidad_puertas: "2",
    cantidad_cajones: "2",
  },
  {
    id: 24,
    img: "https://i.ibb.co/k6cGWnF/Exhibidora-Comercial-BRIKET-Master-3200.jpg",
    title: "Exhibidora Comercial BRIKET Master 3200",
    price: "$00,00",
    category: "freezer",
    marca: "BRIKET",
    capacidad: "315 Litros",
    dimensiones:
      "Ancho: 55cm Prof.: 63cm Alto c/Cenefa: 185.5cm Alto s/Cenefa: 171cm",
    cantidad_puertas: "Triple vidrio Deshidratado entre sí",
    luz_interior: "Si",
    cantidad_estantes: "4 Intercambiables",
    motocompresor: "1/3 HP reforzado",
    niveles_temperatura: "de 0° a +5° C",
    otro: "Ideal para bebidas, lácteos, frutas, verduras, pastas, etc",
  },
  {
    id: 25,
    img: "https://i.ibb.co/HHgybCC/Exhibidora-Comercial-BRIKET-Master-4300.jpg",
    title: "Exhibidora Comercial BRIKET Master 4300",
    price: "$00,00",
    category: "freezer",
    marca: "BRIKET",
    capacidad: "417 Litros",
    cantidad_estantes: "4",
    max_estante: "42 Kg",
    tipo_energia: "D",
    gas: "R 290",
    dimensiones: "Ancho: 65,5cm Prof.: 60cm Alto: 203cm",
    peso: "79 Kg",
  },
  {
    id: 26,
    img: "https://i.ibb.co/PYLQv7R/Exhibidora-Comercial-BRIKET-Master-5000.jpg",
    title: "Exhibidora Comercial BRIKET Master 5000",
    price: "$00,00",
    category: "freezer",
    marca: "BRIKET",
    peso: "95 KG",
    dimensiones: "Ancho: 70cm Prof.: 62cm Alto: 208cm",
    capacidad: "501 Litros",
    cantidad_puertas: "Triple vidrio",
    cantidad_estantes: "4 Estantes Removibles",
    motocompresor: "1/3 Hp",
    niveles_temperatura: "0 a +5°C",
  },
  {
    id: 27,
    img: "https://i.ibb.co/dMVXvjY/Exhibidora-Comercial-Best-Cold-2-Puertas-750l-MT750.webp",
    title: "Exhibidora Comercial BestCold 2 Puertas 750l MT750",
    price: "$00,00",
    category: "freezer",
    marca: "BEST COLD",
    modelo: "MT750",
    capacidad: "750 L",
    orientacion: "Vertical",
    luz_interior: "Sí",
    dimensiones: "Alto: 180cm Prof.: 65cm Ancho: 110cm",
    control_temperatura: "Sí",
    niveles_temperatura: "4 °C - 10 °C",
    cervecera: "Sí",
    cantidad_puertas: "2",
    tipo_puertas: "Batientes",
    descongelamiento: "Automatico",
    motocompresor: "1/3 hp",
  },
  {
    id: 28,
    img: "https://i.ibb.co/9wwKbfT/Freezer-Horizontal-BRIKET-Tapa-Vidrio-3300.jpg",
    title: "Freezer Horizontal BRIKET Tapa Vidrio 3300",
    price: "$00,00",
    category: "freezer",
    marca: "BRIKET",
    modelo: "EH 3300",
    capacidad: "295 L",
    orientacion: "Horizontal",
    cantidad_cajones: "2",
    ruedas: "Sí",
    dimensiones: "Alto: 95cm Prof.: 61cm Ancho 115.5cm",
    tipo_energia: "A",
    gas: "R134",
    motocompresor: "FF1-12HBK",
  },
  {
    id: 29,
    img: "https://i.ibb.co/0cffVH7/Freezer-Horizontal-Teora-550-L-TV-FH550-TV.jpg",
    title: "Freezer Horizontal TEORA 550L TV FH550TV",
    price: "$00,00",
    category: "freezer",
    marca: "TEORA",
    modelo: "FH550TV",
    capacidad: "542 L",
    cantidad_puertas: "2",
    cantidad_cajones: "2",
    dimensiones: "Ancho: 162cm Prof.: 70cm Alto: 84cm",
    niveles_temperatura: "-18°C a +5°C",
    gas: "R-134a",
  },
  {
    id: 30,
    img: "https://i.ibb.co/1nY1FH9/Batea-Comercial-Best-Cold-Standard-Recta-2400-R.jpg",
    title: "Batea Comercial BestCold Standard Recta 2400-R",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "2400-R",
    dimensiones: "Alto: 135cm Prof.: 100cm Ancho: 240cm",
    tipo_gabinete: "Exterior en Chapa",
    termoformado: "Alto Impacto",
    mesa_trabajo: "Acero Inoxidable Brillante",
    luz_interior: "Si",
    gas: "R22",
    otro: "Ideal para Granja, Carniceria, Pescaderia",
  },
  {
    id: 31,
    img: "https://i.ibb.co/RNRTRdr/Vitrina-Mostrador-BESTCOLD-Winnipeg-610-L-1600-WE.jpg",
    title: "Vitrina Mostrador BESTCOLD Winnipeg 610L 1600WE",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "winnipeg 1200",
    capacidad: "240 L",
    orientación: "Horizontal",
    luz_interior: "Sí",
    dimensiones: "Alto: 113cm Prof.: 78cm Ancho: 120cm",
    control_temperatura: "Sí",
    niveles_temperatura: "2 °C - 10 °C",
    cervecera: "Sí",
    material: "Acero",
  },
  {
    id: 32,
    img: "https://i.ibb.co/gj4QR3W/Batea-Comercial-Best-Cold-standard-Vidrio-bajo-1300-rs.jpg",
    title: "Batea Comercial BestCold standard Vidrio bajo 1300-RS",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "1300-RS",
    orientación: "Horizontal",
    luz_interior: "Sí",
    control_temperatura: "Sí",
    niveles_temperatura: "2 °C - 10 °C",
    material: "Acero",
  },
  {
    id: 33,
    img: "https://i.ibb.co/7kM7Cwj/Vitrina-Best-Cold-Winnipeg-Dark-1400-WE.jpg",
    title: "Vitrina BestCold Winnipeg Dark 1400WE",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "Winnipeg Dark 1400WE",
    mesa_trabajo: "Acero Inoxidable",
    termoformado: "Alto impacto",
    cantidad_estantes: "3",
    tipo_puertas: "Batientes Automáticas",
    luz_interior: "Si",
    niveles_temperatura: "2º a 6º c",
    motocompresor: "Embraco 1/4 HP",
    dimensiones: "Ancho: 140 cm. Prof.: 75 cm. Alto: 119 cm",
  },
  {
    id: 34,
    img: "https://i.ibb.co/gy6d8R9/Vitrina-con-Bajada-Best-Cold-450-L-1700-E.jpg",
    title: "Vitrina con Bajada BestCold 450L 1700E",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "2100E",
    dimensiones: "Alto: 113cm Prof.: 78cm Ancho: 210cm",
    mesa_trabajo: "Acero Inoxidable",
    termoformado: "Alto Impacto",
    tipo_puertas: "Batientes",
    control_temperatura: "Digital con Descongelamiento Automatico",
    luz_interior: "Si, Tecnologia LED",
  },
  {
    id: 35,
    img: "https://i.ibb.co/Xs77jkx/Lavarropas-Drean-Next-8-12-ECO.jpg",
    title: "Lavarropas Drean Next 8.12 ECO",
    price: "$00,00",
    category: "lavarropas",
    marca: "DREAN",
    modelo: "8.12 ECO",
    velocidad_centrifugado: "1200 rpm",
    centrifugado: "Sí",
    centrifugado_autoequilibrado: "Sí",
    peso: "71 KG",
    dimensiones: "Alto:	85cm Prof.:	55cm Ancho:	60cm",
    filtro: "Sí",
    tambores: "1 de Acero Inoxidable",
    tipo_lavarropas: "Automatico",
    carga: "Frontal",
    tipo_energia: "A++",
    capacidad: "8 KG",
    lavasecarropas: "No",
    inverter: "No",
    smartphone: "No",
    alarma_final: "Si",
    wifi: "No",
    display: "Si, LED",
    tegnologia: "ECO",
    niveles_temperatura: "Fría, 30°C, 40°C, 60°C, 70°C",
    cantidad_programas: "34",
    tipo_bloqueo: "Bloqueo Panel, Bloqueo Seguridad de Puerta",
    otro: "Lavado Rapido, Funcion Antiarrugas",
  },
  {
    id: 36,
    img: "https://i.ibb.co/cgYJ1mC/Lavasecarropas-Electrolux-8kg-inverter-EWD08-B.png",
    title: "Lavasecarropas Electrolux 8kg inverter EWD08B",
    price: "$00,00",
    category: "lavarropas",
    marca: "ELECTROLUX",
    modelo: "EWD08B",
    dimensiones: "Alto: 85cm Prof.: 57.5cm Ancho: 60cm",
    lavasecarropas: "Sí",
    capacidad_secado: "5 Kg",
    inverter: "Si",
    capacidad: "8 kg",
    carga: "Frotal",
    tipo_energia: "A",
    velocidad_centrifugado: "1200 rpm",
    centrifugado: "Si",
    centrifugado_autoequilibrado: "Si",
    peso: "62.2 kg",
    filtro: "Si",
    tambor: "1, de Acero Inoxidable",
    display: "Si, tipo LED",
    tipo_bloqueo: "Bloqueo de Panel, Bloqueo de Seguridad de Puerta",
    otro: "Funcion Antiarrugas",
  },
  {
    id: 37,
    img: "https://i.ibb.co/D4gfFgd/Lavarropas-Drean-Concept-Fuzzy-Logic-Tech-V1.jpg",
    title: "Lavarropas Drean Concept Fuzzy Logic Tech V1",
    price: "$00,00",
    category: "lavarropas",
    marca: "DREAN",
    modelo: "Fuzzy Logic Tech V1",
    lavasecarropas: "No",
    carga: "Superior",
    tipo_energia: "B",
    capacidad: "5 Kg",
    inverter: "No",
    velocidad_centrifugado: "500 rpm",
    centrifugado: "Si",
    centrifugado_autoequilibrado: "No",
    dimensiones: "Alto: 89cm Prof.: 54cm Ancho: 54cm",
    peso: "33.6 kg",
    cantidad_programas: "15",
    tipo_lavarropas: "Automatico",
    niveles_temperatura: "Fría, Tibia, Caliente",
    filtro: "Si",
    tambor: "1, Polycron",
    display: "Si",
    tipo_bloqueo: "Bloqueo de Puerta",
    otro: "Lavado Rapido, Funcion Antiarrugas",
  },
  {
    id: 38,
    img: "https://i.ibb.co/HqYQFrS/Secarropas-Koh-i-Noor-Negro-N-655-2-5-5-KG.jpg",
    title: "Secarropas Koh i Noor Negro N-655-2 5.5KG",
    price: "$00,00",
    category: "lavarropas",
    marca: "KOH I NOOR",
    modelo: "N-655",
    capacidad: "5.5 kg",
    tambor: "1, de Acero Inoxidable",
    secado: "Centrifugo",
    carga: "Superior",
    dimensiones: "Alto: 63.5cm Diametro: 34.3cm",
    velocidad_centrifugado: "2800 rpm",
    sistema_traba: "Maxima Seguridad TBS",
    tapa: "Abre sola cuando deja de Girar el Tambor",
    otro: "Manija para Transportar, Patas de muy buena sujecion",
    telas: "Algodon, Lana, Toalla, Jean, Lycra, Sintetico, Polyester, etc.",
  },
  {
    id: 39,
    img: "https://i.ibb.co/TLJq7Qc/Secarropas-Koh-i-Noor-Acero-A-665-2-6-5-KG.jpg",
    title: "Secarropas Koh i Noor Acero A-665-2 6.5KG",
    price: "$00,00",
    category: "lavarropas",
    marca: "KOH I NOOR",
    modelo: "A-665",
    capacidad: "6.5 Kg",
    tambor: "1, de Acero Inoxidable",
    carga: "Superior",
    dimensiones: "Alto: 69.5cm Prof.: 34.3cm Ancho: 34.3cm",
    velocidad_centrifugado: "2800 rpm",
    sistema_traba: "Maxima Seguridad TBS",
    tapa: "Abre sola cuando deja de Girar el Tambor",
    otro: "Manija para Transportar, Patas de muy buena sujecion",
    telas: "Algodon, Lana, Toalla, Jean, Lycra, Sintetico, Polyester, etc.",
  },
  {
    id: 40,
    img: "https://i.ibb.co/7zRQrsD/Cocina-Vitta-Bella-Bianca-Multigas.jpg",
    title: "Cocina Vitta Bella Bianca Multigas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Bianca",
    cantidad_hornallas: "4",
    otro: "Mejor Calidad - Mayor durabilidad - Diseño Innovador",
    tipo: "Multigas",
    dimensiones: "Alto: 86cm Prof: 55cm Ancho: 51cm",
    puertas: "Vidrio Templado",
    estilo: "Enlozado con Manija de Hierro de Facil Limpieza",
  },
  {
    id: 41,
    img: "https://i.ibb.co/ChMQmbG/Cocina-Vitta-Bella-Nera-Multigas.jpg",
    title: "Cocina Vitta Bella Nera Multigas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Nera",
    cantidad_hornallas: "4",
    otro: "Mejor Calidad - Mayor durabilidad - Diseño Innovador",
    tipo: "Multigas",
    dimensiones: "Alto: 86cm Prof: 55cm Ancho: 51cm",
    puertas: "Vidrio Templado",
    estilo: "Enlozado con Manija de Hierro de Facil Limpieza",
  },
  {
    id: 42,
    img: "https://i.ibb.co/pxFrvGj/Cocina-Vitta-Bella-Acero-Multigas.jpg",
    title: "Cocina Vitta Bella Acero Multigas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Acero",
    cantidad_hornallas: "4",
    otro: "Mejor Calidad - Mayor durabilidad - Diseño Innovador",
    tipo: "Multigas",
    dimensiones: "Alto: 86cm Prof: 55cm Ancho: 51cm",
    puertas: "Vidrio Templado",
    estilo: "Enlozado con Manija de Hierro de Facil Limpieza",
  },
  {
    id: 43,
    img: "https://i.ibb.co/0y57wXV/Cocina-Vitta-Semi-Industrial-Bella-Chef.jpg",
    title: "Cocina Vitta Semi Industrial Bella Chef",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Chef - Semi Industrial",
    dimensiones: "Alto 86cm, Prof.: 58cm Ancho: 55cm",
    piso: "Ladrillo Refractario",
    puertas: "Vidrio Templado",
    estilo:
      "Rejas de Fundicion, Acero Inoxidable Esmerilado con Pirometro en Puerta",
  },
  {
    id: 44,
    img: "https://i.ibb.co/Trp8wGz/Cocina-Electrolux-Doble-Horno-Elec-Gas.jpg",
    title: "Cocina Electrolux Doble Horno Elec-Gas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "ELECTROLUX",
    modelo: "56DXQ",
    grill: "No",
    temporizador: "Si",
    comando_tactil: "No",
    horno_autolimpiante: "No",
    cantidad_hornallas: "4",
    peso: "46.5 kg",
    dimensiones: "Alto: 146.5cm Ancho: 56cm Prof.: 107.4cm",
    alimentacion: "Gas y Electrica",
    industrial: "No",
    capacidad_horno: "106.5 Litros",
    horno_doble: "Si",
    parrillas: "3",
    tipo_energia: "A",
    tapa: "Si",
  },
  {
    id: 45,
    img: "https://i.ibb.co/BgH66Jw/Cocina-Industrial-Motta-Pro-Pv-520-G-N.jpg",
    title: "Cocina Industrial Motta Pro Pv 520 G-N",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "MOTTA",
    modelo: "MO520PVN",
    dimensiones: "Alto: 86cm Prof.: 55cm Ancho: 53cm",
    cantidad_hornallas: "4",
    puertas: "Vidrio Color Negro",
    grill: "Si, Inferior",
    otro: "Rejas de Fundicion, Exterior de Acero Inox. interior Enlozado",
    parrillas: "2",
  },
  {
    id: 46,
    img: "https://i.ibb.co/yhf9DCf/Cocina-Industrial-Motta-Pro-600-Negra-G-N.jpg",
    title: "Cocina Industrial Motta Pro 600 Negra G-N",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "MOTTA",
    modelo: "Pro 600 Negra G-N",
    dimensiones: "Alto: 86cm Prof.: 64cm Ancho: 59cm",
    cantidad_hornallas: "4",
    puertas: "Vidrio Color Negro",
    grill: "Si, Inferior",
    otro: "Rejas de Fundicion, Exterior de Acero Inox. interior Enlozado",
    parrillas: "2",
  },
  {
    id: 47,
    img: "https://i.ibb.co/5jXGPdX/Cocina-Industrial-Compacta-El-Gauchito-G-N.jpg",
    title: "Cocina Industrial Compacta El Gauchito G-N",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "EL GAUCHITO",
    modelo: "550",
    industrial: "Si",
    cantidad_hornallas: "4",
    valvula_seguridad: "Si",
    tapa: "No",
    puerta_horno: "Ciega",
    horno_doble: "No",
    temporizador: "No",
  },
  {
    id: 48,
    img: "https://i.ibb.co/5cMQKMT/Horno-Electrico-Vitta-Forno-blanco-45l-c-Anafe.jpg",
    title: "Horno Electrico Vitta Forno blanco 45l c-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno Bianco",
    capacidad_horno: "45 Litros",
    potencia: "1600 W",
    dimensiones: "Alto: 35cm, Prof.: 38cm, Ancho: 54cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
  },
  {
    id: 49,
    img: "https://i.ibb.co/qYT4vS3/Horno-Vitta-Electrico-DW-5094-CA-55-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico DW-5094CA 55L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno NERO",
    capacidad_horno: "55 Litros",
    potencia: "2000 W",
    dimensiones: "Alto: 37cm, Prof.: 42cm, Ancho: 56cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
    otro: "Pizza Bump",
  },
  {
    id: 50,
    img: "https://i.ibb.co/qYT4vS3/Horno-Vitta-Electrico-DW-5094-CA-55-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico DW-7004CA 70L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno NERO",
    capacidad_horno: "70 Litros",
    potencia: "2080 W",
    dimensiones: "Alto: 39cm, Prof.: 46cm, Ancho: 58cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
    otro: "Pizza Bump",
  },
  {
    id: 51,
    img: "https://i.ibb.co/LxQW8jG/Horno-Vitta-Electrico-Forno-Rosso-45-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico Forno Rosso 45L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno ROSSO",
    capacidad_horno: "45 Litros",
    potencia: "1600 W",
    dimensiones: "Alto: 35cm, Prof.: 38cm, Ancho: 54cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
  },
  {
    id: 52,
    img: "https://i.ibb.co/8BdkZhH/Horno-Vitta-Electrico-Forno-Rosso-55-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico Forno Rosso 55L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno ROSSO",
    capacidad_horno: "55 Litros",
    potencia: "2000 W",
    dimensiones: "Alto: 37cm, Prof.: 42cm, Ancho: 56cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
  },
  {
    id: 53,
    img: "https://i.ibb.co/MnM0KvS/Horno-Vitta-Electrico-40l-VIT-HE4000012000-RC-1.jpg",
    title: "Horno Vitta Electrico 40l-50l-65l",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "HE4000- HE5000- HE6500",
    capacidad: "40 Litros, 50 Litros & 65 Litros",
    funcion: "Espiedo",
    anafe: "Doble",
    potencia: "2000W",
    niveles_temperatura: "250 Cº",
    otro: "Incluye Bandeja y 2 Pinzas",
  },
  {
    id: 200,
    img: 3112,
    title: "Bajo Mesada 2 Puertas 3 Cajones Jacaranda 3030",
    price: "$00,00",
    category: "mueblesdecocina",
    detail:
      "Bajo mesada de 2 puertas y 3 cajones. Medidas de 1400 x 800 x 470MM. SE ENTREGA DESARMADO",
    codigo: 3112,
  },
  {
    id: 201,
    img: 3111,
    title: "Bajo Mesada 2 Puertas 3 Cajones Blanco 3028",
    price: "$00,00",
    category: "mueblesdecocina",
    detail:
      "Bajo mesada de 2 puertas y 3 cajones. Medidas de 1400 x 800 x 470MM. SE ENTREGA DESARMADO",
    codigo: 3111,
  },
  {
    id: 202,
    img: 656,
    title: "Alacena 3 Puertas Jacaranda 2023",
    price: "$00,00",
    detail: "",
    category: "mueblesdecocina",
    codigo: 656,
  },
  {
    id: 203,
    img: 650,
    title: "Alacena 3 Puertas Blanco/Wengue 2022",
    price: "$00,00",
    detail: "",
    category: "mueblesdecocina",
    codigo: 650,
  },
  {
    id: 203,
    img: 650,
    title: "Alacena 3 Puertas Blanco/Wengue 2022",
    price: "$00,00",
    detail: "",
    category: "mueblesdecocina",
    codigo: 650,
  },
  {
    id: 204,
    img: 3428,
    title: "Mesa de Luz 1 Puerta 1 Cajon Puerta Linosa 110",
    price: "$00,00",
    detail: "Un cajon / una puerta. 415 x 595 x 315 mm. SE ENTREGA DESARMADO",
    category: "mueblesdeinterior",
    codigo: 3428,
  },
  {
    id: 205,
    img: 646,
    title: "Mesa de Luz 1 Puerta 1 Cajon Wengue 99",
    price: "$00,00",
    detail: "Un cajon / una puerta. 415 x 595 x 315 mm. SE ENTREGA DESARMADO",
    category: "mueblesdeinterior",
    codigo: 646,
  },
  {
    id: 206,
    img: 645,
    title: "Mesa de Luz 1 Puerta 1 Cajon jacaranda 108",
    price: "$00,00",
    detail: "Un cajon / una puerta. 415 x 595 x 315 mm. SE ENTREGA DESARMADO",
    category: "mueblesdeinterior",
    codigo: 645,
  },
  {
    id: 207,
    img: 644,
    title: "Placard Bahia 5 puertas 2 cajones wengue 3513",
    price: "$00,00",
    detail:
      "Linea nordica con 5 puertas y 2 cajones correderas metalicas. 1510mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 644,
  },
  {
    id: 208,
    img: 642,
    title: "Placard Bahia 5 puertas 2 cajones jacaranda 3514",
    price: "$00,00",
    detail:
      "Linea nordica con 5 puertas y 2 cajones correderas metalicas. 1510mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 642,
  },
  {
    id: 209,
    img: 643,
    title: "Placard Bahia 5 puertas 2 cajones venecia 3515",
    price: "$00,00",
    detail:
      "Linea nordica con 5 puertas y 2 cajones correderas metalicas. 1510mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 643,
  },
  {
    id: 210,
    img: 635,
    title: "Placard Bahia 4 puertas 2 cajones jacaranda 3524",
    price: "$00,00",
    detail:
      "Linea nordica con 4 puertas y 2 cajones correderas metalicas. 1210mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 635,
  },
  {
    id: 211,
    img: 636,
    title: "Placard Bahia 4 puertas 2 cajones venecia 3525",
    price: "$00,00",
    detail:
      "Linea nordica con 4 puertas y 2 cajones correderas metalicas. 1210mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 636,
  },
  {
    id: 212,
    img: 637,
    title: "Placard Bahia 4 puertas 2 cajones wengue 3523",
    price: "$00,00",
    detail:
      "Linea nordica con 4 puertas y 2 cajones correderas metalicas. 1210mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 637,
  },
  {
    id: 213,
    img: 634,
    title: "Placard Bahia 3 puertas 2 cajones wengue 3533",
    price: "$00,00",
    detail:
      "Linea nordica con 3 puertas y 2 cajones correderas metalicas. 914mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 634,
  },
  {
    id: 214,
    img: 632,
    title: "Placard Bahia 3 puertas 2 cajones venecia 3525",
    price: "$00,00",
    detail:
      "Linea nordica con 3 puertas y 2 cajones correderas metalicas. 914mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 632,
  },
  {
    id: 215,
    img: 631,
    title: "Placard Bahia 3 puertas 2 cajones jacaranda 3534",
    price: "$00,00",
    detail:
      "Linea nordica con 3 puertas y 2 cajones correderas metalicas. 914mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 631,
  },
  {
    id: 216,
    img: 3301,
    title: "Placard Bahia 2 puertas 2 cajones blanco 3542",
    price: "$00,00",
    detail:
      "Linea nordica con 2 puertas y 2 cajones correderas metalicas. 610mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 3301,
  },
  {
    id: 217,
    img: 629,
    title: "Placard Bahia 2 puertas 2 cajones venecia 3545",
    price: "$00,00",
    detail:
      "Linea nordica con 2 puertas y 2 cajones correderas metalicas. 610mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 629,
  },
  {
    id: 218,
    img: 630,
    title: "Placard Bahia 2 puertas 2 cajones wengue 3543",
    price: "$00,00",
    detail:
      "Linea nordica con 2 puertas y 2 cajones correderas metalicas. 610mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 630,
  },
  {
    id: 219,
    img: 628,
    title: "Placard Bahia 2 puertas 2 cajones jacaranda 3544",
    price: "$00,00",
    detail:
      "Linea nordica con 2 puertas y 2 cajones correderas metalicas. 610mm x 1835mm x 460mm. Se entrega desarmado",
    category: "mueblesdeinterior",
    codigo: 628,
  },
  {
    id: 220,
    img: 3342,
    title: "Bicicleta enrique r20 nena stars",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3342,
  },
  {
    id: 221,
    img: 2530,
    title: "Bicicleta paseo c/canasto tempo rod 20 dama",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 2530,
  },
  {
    id: 222,
    img: 2524,
    title: "Bicicleta alpina rod 26 18 vel hombre",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 2524,
  },
  {
    id: 223,
    img: 3102,
    title: "Bicicleta enrique r29 gris/naranja",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3102,
  },
  {
    id: 224,
    img: 3204,
    title: "Bicicleta enrique fenix r29 blanco",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3204,
  },
  {
    id: 225,
    img: 3202,
    title: "Bicicleta enrique fenix r29 azul",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3202,
  },
  {
    id: 226,
    img: 3732,
    title: "Bicicleta corvo r29 21 velocidades negra",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3732,
  },
  {
    id: 227,
    img: 3734,
    title: "Bicicleta corvo r29 21 velocidades celeste",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3734,
  },
  {
    id: 228,
    img: 3731,
    title: "Bicicleta corvo r29 21 velocidades blanca",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3731,
  },
  {
    id: 229,
    img: 3733,
    title: "Bicicleta corvo r29 21 velocidades roja",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3733,
  },
  {
    id: 230,
    img: 3696,
    title: "Bicicleta lamborhini shimano r29 m47l azul/negro",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3696,
  },
  {
    id: 231,
    img: 3691,
    title: "Bicicleta lamborhini shimano r29 m45l rojo/negro",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3691,
  },
  {
    id: 232,
    img: 3690,
    title: "Bicicleta lamborhini shimano r29 m52l gris/negro",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3690,
  },
  {
    id: 233,
    img: 3489,
    title: "Bicicleta lamborhini shimano r29 m02l m/negro",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3489,
  },
  {
    id: 234,
    img: 2585,
    title: "Bicicleta lamborghini c/21 r29 m37l neg/verde",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 2585,
  },
  {
    id: 235,
    img: 3070,
    title: "Bicicleta lamborghini c/21 r29 m58l blanco/naranja",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3070,
  },
  {
    id: 236,
    img: 3427,
    title: "Bicicleta lamborghini c/21 r29 s02l s/negro",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3427,
  },
  {
    id: 237,
    img: 3660,
    title: "Bicicleta lamborghini shimano r29 m60l plata/negro",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3660,
  },
  {
    id: 238,
    img: 3495,
    title: "Bicicleta lamborghini shimano r29 m36l gris/verde",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3495,
  },
  {
    id: 239,
    img: 3486,
    title: "Bicicleta lamborghini shimano r29 m23l blanco/negro",
    price: "$00,00",
    detail: "",
    category: "bicicletas",
    codigo: 3486,
  },
  {
    id: 240,
    img: 2564,
    title: "pileta estructural 6100l 3.60 x 0.76 avenli",
    price: "$00,00",
    detail:
      "De fácil instalación rápida y sin herramientas. Estructura de metal resistente al óxido, le dan una larga vida útil. Paredes laterales de PVC y poliéster de alta resistencia proporciona gran durabilidad. Sistema anticorrosión Tech Trigonal Lock. Kit de reparación. Medidas: Ø 3,60 mt | Altura 0,76 mt. Medidas caja: 32,5 x 20,0 x 119,0 cm. Peso: 22,4 kg",
    category: "piletas",
    codigo: 2564,
  },
  {
    id: 241,
    img: 2473,
    title: "pileta mor 400 l 1.15 x 1.06 x 0.33 1919",
    price: "$00,00",
    detail:
      "Los productos de la marca brasilera Mor son reconocidos por ser innovadores de calidad y estar enfocados a sus usuarios. Con esta pileta, podrás disfrutar del verano y pasar placenteramente los días de calor. Para todo tipo de espacios. Por su forma rectangular y su tamaño amplio y cómodo de 1.15 m de largo y 1.06 m de ancho, los meses de calor serán tus preferidos del año para compartir momentos únicos junto a quienes más querés.",
    category: "piletas",
    codigo: 2473,
  },
  {
    id: 242,
    img: 2474,
    title: "pileta mor 1000 l 1.89 x 1.26 x 0.42 1921",
    price: "$00,00",
    detail:
      "Los productos de la marca brasilera Mor son reconocidos por ser innovadores de calidad y estar enfocados a sus usuarios. Con esta pileta, podrás disfrutar del verano y pasar placenteramente los días de calor. Para todo tipo de espacios. Por su forma rectangular y su tamaño amplio y cómodo de 1.15 m de largo y 1.06 m de ancho, los meses de calor serán tus preferidos del año para compartir momentos únicos junto a quienes más querés. Comodidad y cuidado. Con su válvula de desagüe, vas a poder sacar el agua de una manera mucho más rápida y simple cuando desees limpiarla o vaciarla.",
    category: "piletas",
    codigo: 2474,
  },
  {
    id: 243,
    img: 2475,
    title: "pileta mor 1500 l 1.89 x 1.89 x 0.42 1924",
    price: "$00,00",
    detail:
      "Los productos de la marca brasilera Mor son reconocidos por ser innovadores de calidad y estar enfocados a sus usuarios. Con esta pileta, podrás disfrutar del verano y pasar placenteramente los días de calor. Para todo tipo de espacios. Por su forma rectangular y su tamaño amplio y cómodo de 1.15 m de largo y 1.06 m de ancho, los meses de calor serán tus preferidos del año para compartir momentos únicos junto a quienes más querés. Comodidad y cuidado. Con su válvula de desagüe, vas a poder sacar el agua de una manera mucho más rápida y simple cuando desees limpiarla o vaciarla.",
    category: "piletas",
    codigo: 2475,
  },
  {
    id: 244,
    img: 2476,
    title: "pileta mor 2000 l 2.11 x 1.64 x 0.58 1922",
    price: "$00,00",
    detail:
      "Los productos de la marca brasilera Mor son reconocidos por ser innovadores de calidad y estar enfocados a sus usuarios. Con esta pileta, podrás disfrutar del verano y pasar placenteramente los días de calor. Para todo tipo de espacios. Por su forma rectangular y su tamaño amplio y cómodo de 1.15 m de largo y 1.06 m de ancho, los meses de calor serán tus preferidos del año para compartir momentos únicos junto a quienes más querés. Comodidad y cuidado. Con su válvula de desagüe, vas a poder sacar el agua de una manera mucho más rápida y simple cuando desees limpiarla o vaciarla.",
    category: "piletas",
    codigo: 2476,
  },
  {
    id: 245,
    img: 582,
    title: "Parrilla electrica kanji zoilo ",
    price: "$00,00",
    detail:
      "2000W ·  Control automático con termostato ·  Con deflector ·  Manijas de tacto frías ·  Potencia 220-240V ~ 50 /60Hz",
    category: "parrillas",
    codigo: 582,
  },
  {
    id: 246,
    img: 2709,
    title: "Parrilla electrica kanji gaucho kjh-be220pn ",
    price: "$00,00",
    detail:
      "2000W ·  Control automático con termostato ·  Con deflector ·  Manijas de tacto frías ·  Potencia 220-240V ~ 50 /60Hz",
    category: "parrillas",
    codigo: 2709,
  },
  {
    id: 247,
    img: 468,
    title: "gas butano cartucho descartable de 227 grs 466-l ",
    price: "$00,00",
    detail: "Cartucho BROGAS descartable de 227 gr. Gas butano. ",
    category: "parrillas",
    codigo: 468,
  },
  {
    id: 248,
    img: 2498,
    title: "cortador de pasto naftera vitta 4.5hp hogareña r60 ",
    price: "$00,00",
    detail:
      "ancho de corte 18´. cuchilla recolectora c/trat. termico. carcasa de acero estampado. rodado delantero 160. rodado trasero 180. altura de corte 6 pos. motor serie 450etm. capacidad de combustible 1.5l ",
    category: "cortadoras",
    codigo: 2498,
  },
  {
    id: 249,
    img: 2102,
    title: "hidrolavadora 1200w konan ",
    price: "$00,00",
    detail:
      "Con tu hidrolavadora podés dejar reluciente cualquier material o superficie. Su rocío de agua de alta presión es entre diez y cincuenta veces más potente que las mangueras de jardín, lo que hace más eficaz y fácil el proceso de limpieza. ",
    category: "hidrolavadoras",
    codigo: 2102,
  },
  {
    id: 250,
    img: 2293,
    title: "motosierra electrica black and decjer ic04114566n ",
    price: "$00,00",
    detail:
      "Ajuste de cadena y freno anti-retroceso permite ajustar la tensión de la cadena y la detiene automáticamente. Longitud máxima de corte de 40cm 16´ para mayor versatilidad y rápidez de corte. Lubricación automática para maximizar el rendimiento de corte. Interruptor de bloqueo previene encendidos accidentales. Liviana, pesa solo 2,6kg (5,8lb) para facilidad de uso ",
    category: "herramientas",
    codigo: 2293,
  },
  {
    id: 251,
    img: 455,
    title: "lijadora orbital 150w hyundai hh0s150 019-6040 ",
    price: "$00,00",
    detail:
      "Con esta lijadora lograrás trabajos de mayor calidad para tus clientes, ya que te permitirá realizar tareas de lijado en diferentes materiales con el mejor resultado. ¡Conseguí detalles únicos!. Practicidad y versatilidad en una sola herramienta. Con la lijadora Hyundai HH0S150 lograrás trabajos con un acabado más fino y llegarás a lugares estrechos y de difícil acceso. Una herramienta compacta, versátil y con un diseño ergonómico, que te proporciona más control y comodidad. ¡Es ideal si tu actividad principal es la carpintería!",
    category: "herramientas",
    codigo: 455,
  },
  {
    id: 252,
    img: 620,
    title: "lijadora orbital mano konan 200w + 3 lijas ",
    price: "$00,00",
    detail:
      "LIJADORA DE PALMA - ORBITAL - KONAN * 200W DE POTENCIA * 19000 RPM * LIJA DE 100 X 110 SIN ABROJO  * INCLUYE 2 LIJAS",
    category: "herramientas",
    codigo: 620,
  },
  {
    id: 253,
    img: 605,
    title: "lijadora orbital konan 250w + 3 lijas kloe/250 ",
    price: "$00,00",
    detail:
      "Lijadora Orbital 250 W c/ 3 Lijas #KLOE/250 Detalle  Potencia 250 w  Potencia de entrada: 250W.  Voltaje nominal: 220v - 50Hz. Frecuencia nominal: 60 Hz. Velocidad sin carga: 10000 R/Min. Tamaño del papel de lija: 185 x 93 mm. Altura / Ancho: 15 cm. / 23.5 cm.",
    category: "herramientas",
    codigo: 605,
  },
  {
    id: 254,
    img: 935,
    title: "pulidora 9 fligman 1300w cp1801200 ",
    price: "$00,00",
    detail: "",
    category: "herramientas",
    codigo: 935,
  },
  {
    id: 255,
    img: 2312,
    title: "lijadora orbital de palma black and decker 200w ",
    price: "$00,00",
    detail:
      "- Potente motor de 200 W para preparación de superficies - Interruptor de sellado para mayor durabilidad - Diseño compacto para mayor comodidad y versatilidad - Retenedor de papel ideal para cambios rápidos y fáciles de papel - Diseño ergonómico para mayor comodidad y control - Velocidad 14000/min (opm) - Cable de 2 mts - Peso aproximado 1,1 kg - Apta para lijar: Maderas y metales - No utilizar en lijado de pared, durlock u otros materiales de construcción",
    category: "herramientas",
    codigo: 2312,
  },
  {
    id: 256,
    img: 600,
    title: "sierra circular konan 1300w + disco kcs/1300 ",
    price: "$00,00",
    detail:
      "La sierra Konan KCS/1300 es la solución para realizar cortes con precisión y velocidad. Es un producto que hace la tarea más fácil y por lo tanto es excelente para equipar un taller o una carpintería, ya sea profesional o amateur. Diámetro del disco. Su disco de 184mm posibilita cortes definidos y prolijos, difíciles de alcanzar de manera manual.",
    category: "herramientas",
    codigo: 600,
  },
  {
    id: 257,
    img: 2299,
    title: "sierra cilrcular stanley 1600w 190mm ic04114566n ",
    price: "$00,00",
    detail:
      "La marca Stanley fabrica herramientas desde 1843, con la premisa de ofrecer un producto preciso, confiable y resistente. La sierra SC16 está pensada para que puedas conseguir resultados profesionales en tu trabajo. Diámetro del disco. Su disco de 190mm posibilita cortes definidos y prolijos, difíciles de alcanzar de manera manual.",
    category: "herramientas",
    codigo: 2299,
  },
  {
    id: 258,
    img: 3060,
    title: "sierra circular philco 1200w mepsc115 ",
    price: "$00,00",
    detail:
      "La sierra Philco MEPSC115 es la solución para realizar cortes con precisión y velocidad. Es un producto que hace la tarea más fácil y por lo tanto es excelente para equipar un taller o una carpintería, ya sea profesional o amateur. Diámetro del disco. Su disco de 185mm posibilita cortes definidos y prolijos, difíciles de alcanzar de manera manual.",
    category: "herramientas",
    codigo: 3060,
  },
  {
    id: 259,
    img: 1843,
    title: "sierra caladora 350w ",
    price: "$00,00",
    detail:
      "Gracias a la trayectoria de la empresa Philco, podemos identificar la calidad, versatilidad e innovación de sus productos y herramientas a nivel internacional. Seguridad al trabajar. Al momento de utilizar la sierra, el interruptor de bloqueo evita que sea accionada de manera accidental. Es necesario verificar siempre que la herramienta se encuentra bloqueada antes de comenzar a trabajar.",
    category: "herramientas",
    codigo: 1843,
  },
  {
    id: 260,
    img: 623,
    title: "sierra caladora konan 750w +3 luz led ",
    price: "$00,00",
    detail:
      "Sierra Caladora 750 W c/ Luz Led - #KSCL/750 - Detalle Potencia 750 w - Potencia de entrada: 750W - Voltaje nominal: 220v - 50Hz - Frecuencia nominal: 60 Hz - Velocidad sin carga: 0-3000 RPM - Tapa de corte: 65 mm.",
    category: "herramientas",
    codigo: 623,
  },
  {
    id: 261,
    img: 2294,
    title: "sierra caladora black and decker ic04113319x ",
    price: "$00,00",
    detail:
      "- Velocidad Variable - Cambio de las Hojas de Sierra sin Herramientas - Baja Vibración - Función Soplador que Mantiene la Línea de Corte Limpia - Línea de Corte Visible para un Corte Más Preciso - Encastre Rápido",
    category: "herramientas",
    codigo: 2294,
  },
  {
    id: 262,
    img: 1420,
    title: "amoladora philco angular",
    price: "$00,00",
    detail:
      "La amoladora Philco es una herramienta versátil, que permite realizar diferentes trabajos con una terminación profesional. Por eso, es una excelente opción sumarla a tu taller o caja de herramientas. Equipá tu casa o taller y ¡hacelo vos mismo! Esta amoladora angular es perfecta para realizar distintos trabajos de amolado, cepillado y pulido. A su vez, se destaca por ser un elemento indispensable para cortar, desbastar y lijar diversos materiales derivados del metal. Segura y fácil de maniobrar. A la hora de trabajar con herramientas es importante que tu seguridad esté garantizada. Con el botón de bloqueo de disco que trae incorporado reducís al máximo el riesgo cuando trabajás con discos de corte.",
    category: "herramientas",
    codigo: 1420,
  },
  {
    id: 263,
    img: 103,
    title: "amoladora angular black and decker 820w g720n",
    price: "$00,00",
    detail:
      "La amoladora Black+Decker es una herramienta versátil, que permite realizar diferentes trabajos con una terminación profesional. Por eso, es una excelente opción sumarla a tu taller o caja de herramientas. Con la amoladora angular Black+Decker G720N vas a poder realizar distintos trabajos de corte y pulido. Tiene un potente motor de 820 W y cuenta con empuñadura lateral de 3 posiciones. Además, su avanzado sistema de seguridad incorporado la vuelven un dispositivo ideal para tu taller. Segura y fácil de maniobrar. A la hora de trabajar con herramientas es importante que tu seguridad esté garantizada. Con el botón de bloqueo de disco que trae incorporado reducís al máximo el riesgo cuando trabajás con discos de corte.",
    category: "herramientas",
    codigo: 103,
  },
  {
    id: 264,
    img: 2364,
    title: "amoladora angular stanley 115mm 150w sgs1045",
    price: "$00,00",
    detail:
      "Marca: Stanley - Modelo:SGS1045 Características: • Potencia 1050 w • Velocidad 11000 RPM • Diámetro de disco 115 mm • Incluye, llave de ajuste, mango lateral y manual • Peso aproximado 2,5 Kg",
    category: "herramientas",
    codigo: 2364,
  },
  {
    id: 265,
    img: 2391,
    title: "taladro ator a bateria konan 13mm 21v ",
    price: "$00,00",
    detail:
      "CARACTERISTICAS: TALADRO ATORNILLADOR PERCUTOR - CON 2 BATERIAS - VELOCIDAD SIN CARGA : 0-400 RPM / 0-1350 RPM - PORTABOCAS : 13MM - INCLUYE 2 PUNTAS DOBLES - INCLUYE CARGADOR DE BATERIA -INCLUYE 2 BATERIAS -VOLTAJE : 220V-50HZ - VELOCIDAD SIN CARGA : 0-400 RPM / 0-1350 RPM - PORTABROCAS : 13MM -CAPACIDAD DE LA BATERIA 1.5 AMP  -TORQUE MAXIMO: 29N.M.",
    category: "herramientas",
    codigo: 2391,
  },
  {
    id: 266,
    img: 3189,
    title: "taladro atornillador b&d 12v a bat 10mm cd121k",
    price: "$00,00",
    detail:
      "Descripción: ¡Pensá en todos los proyectos que te gustaría hacer, ahora es el momento de crearlos! Gracias a la innovación y evolución constante en la gama de herramientas Black+Decker, tendrás la confianza para realizar cualquier tarea. Sus taladros son potentes, compactos y podrás utilizarlos en múltiples aplicaciones; tienen una vida útil prolongada, para que puedas trabajar sin problemas año tras año. Empezá a ser creativo hoy y mirá a dónde te lleva. Tecnología de excelencia. Su mandril de 10 mm te permitirá manipular fácilmente la herramienta de manera segura y precisa. Además, su velocidad variable ofrece una gran experiencia de uso, adaptada a tus necesidades y requerimentos. Ligero y fácil de manejar. Al no haber cables de por medio, vas a sentirte más cómodo al manipularlo. Además, causa menos fatiga tras un uso intensivo. No se presentarán problemas como no encontrar un contacto o que el cable sea muy corto para el área donde lo vas a utilizar.",
    category: "herramientas",
    codigo: 3189,
  },
  {
    id: 267,
    img: 2296,
    title: "taladro atorn bateria dewalt 12v ico4113319x",
    price: "$00,00",
    detail:
      "Descripción: DeWalt es innovación que hace la diferencia y sinónimo de solidez. Desde 1922 continúa diseñando y optimizando soluciones industriales para asegurar el desempeño en las condiciones más difíciles. Cada producto está orientado a maximizar el tiempo de uso y alcanzar el más alto rendimiento en la industria. Sus taladros se caracterizan por un diseño compacto, ligero y ergonómico que te brindará comodidad y seguridad. Tecnología de excelencia. Su mandril de 10 mm te permitirá manipular fácilmente la herramienta de manera segura y precisa. Además, su velocidad variable ofrece una gran experiencia de uso, adaptada a tus necesidades y requerimentos. Versatilidad y eficiencia. Su función destornilladora te posibilitará explotar al máximo tu producto. Podrás realizar aplicaciones de diferentes magnitudes con gran exactitud y calidad. Ligero y fácil de manejar. Al no haber cables de por medio, vas a sentirte más cómodo al manipularlo. Además, causa menos fatiga tras un uso intensivo. No se presentarán problemas como no encontrar un contacto o que el cable sea muy corto para el área donde lo vas a utilizar.",
    category: "herramientas",
    codigo: 2296,
  },
  {
    id: 268,
    img: 3393,
    title: "taladro a bateria hyundai 12v + maletin hp0322",
    price: "$00,00",
    detail:
      "Descripción: TALADRO A BATERIA HYUNDAI 12V 10MM * Voltaje 12V * Corriente: 2.0A * Potencia: 45W *  Mandril: 3/8´ * Velocidad: 0-900 RPM * Torque máximo: 15nm * Posiciones torque 19+1. Incluye: Batería - Cargador -  6 puntas de destornillador  -  6 mechas - 1 alargue magnético de 60 nm",
    category: "herramientas",
    codigo: 3393,
  },
  {
    id: 269,
    img: 2300,
    title: "taladro inalambrico percutor stanley 12v 10mm",
    price: "$00,00",
    detail:
      "Descripción: Desde su fundación en 1843, Stanley se ha comprometido a proporcionar productos resistentes, pioneros y adecuados para cualquier tarea a los profesionales de todo el mundo. Cada herramienta Stanley se ha creado para ayudarte a trabajar mejor, de manera más inteligente y con mayor rapidez. Sus taladros se caracterizan por un diseño compacto y liviano para un desempeño continuo en áreas reducidas. Podrás realizar una gran variedad de trabajos de perforación y fijación en diversos materiales. Tecnología de excelencia. Su mandril de 10 mm te permitirá manipular fácilmente la herramienta de manera segura y precisa. Además, su velocidad variable ofrece una gran experiencia de uso, adaptada a tus necesidades y requerimentos. Versatilidad y eficiencia. Utilizalo para las aplicaciones que desees. Al ser percutor y destornillador podrás explotar al máximo sus funciones y obtener exactitud y calidad. Ligero y fácil de manejar. Al no haber cables de por medio, vas a sentirte más cómodo al manipularlo. Además, causa menos fatiga tras un uso intensivo. No se presentarán problemas como no encontrar un contacto o que el cable sea muy corto para el área donde lo vas a utilizar.",
    category: "herramientas",
    codigo: 2300,
  },
  {
    id: 270,
    img: 613,
    title: "taladro percutor stanley 13mm 600w ",
    price: "$00,00",
    detail:
      "Descripción: Desde su fundación en 1843, Stanley se ha comprometido a proporcionar productos resistentes, pioneros y adecuados para cualquier tarea a los profesionales de todo el mundo. Cada herramienta Stanley se ha creado para ayudarte a trabajar mejor, de manera más inteligente y con mayor rapidez. Sus taladros se caracterizan por un diseño compacto y liviano para un desempeño continuo en áreas reducidas. Podrás realizar una gran variedad de trabajos de perforación y fijación en diversos materiales. Tecnología de excelencia. Su mandril de 10 mm te permitirá manipular fácilmente la herramienta de manera segura y precisa. Además, su velocidad variable ofrece una gran experiencia de uso, adaptada a tus necesidades y requerimentos. Versatilidad y eficiencia. Utilizalo para las aplicaciones que desees. Al ser percutor y destornillador podrás explotar al máximo sus funciones y obtener exactitud y calidad. Ligero y fácil de manejar. Al no haber cables de por medio, vas a sentirte más cómodo al manipularlo. Además, causa menos fatiga tras un uso intensivo. No se presentarán problemas como no encontrar un contacto o que el cable sea muy corto para el área donde lo vas a utilizar.",
    category: "herramientas",
    codigo: 613,
  },
  {
    id: 271,
    img: 2905,
    title: "taladro percutor b&d 13mm 560w tm555 ",
    price: "$00,00",
    detail:
      "¡Pensá en todos los proyectos que te gustaría hacer, ahora es el momento de crearlos! Gracias a la innovación y evolución constante en la gama de herramientas Black+Decker, tendrás la confianza para realizar cualquier tarea. Sus taladros son potentes, compactos y podrás utilizarlos en múltiples aplicaciones; tienen una vida útil prolongada, para que puedas trabajar sin problemas año tras año. Empezá a ser creativo hoy y mirá a dónde te lleva. Tecnología de excelencia. Su mandril de 13 mm te permitirá manipular fácilmente la herramienta de manera segura y precisa. Además, su velocidad variable ofrece una gran experiencia de uso, adaptada a tus necesidades y requerimentos. Versatilidad y eficiencia. Utilizalo para las aplicaciones que desees. Al ser percutor y destornillador podrás explotar al máximo sus funciones y obtener exactitud y calidad.",
    category: "herramientas",
    codigo: 2905,
  },
  {
    id: 272,
    img: 1900,
    title: "taladro hyundai 550w 72 piezas + maletin  ",
    price: "$00,00",
    detail:
      "Descripción: TALADRO HYUNDAI HYID-0111 CON 72 ACCESORIOS.  TALADRO HYUNDAI 550W  Potencia - 550w  Voltaje - 230v-50hz  Diámetro del mandril - 13mm  Velocidad variable 1200 RMP a 2800 rpm.  INCLUYE: 1 Maletín * 40 Puntas de destornillador de 25mm de largo * 12 Puntas de destornillador de 50mm de largo * 1 Adaptador * 5 Mechas para madera * 9 Mechas para metal * 3 Llaves hexagonales * 3 tubos hexagonales * 1 Llave Auxiliar * 1 Mandril * 1 Medidor de profundidad",
    category: "herramientas",
    codigo: 1900,
  },
  {
    id: 273,
    img: 3641,
    title: "parlante crown mustang negro bluetooth sbl-6500bt  ",
    price: "$00,00",
    detail:
      "Descripción: Crown Mustang SBL-6500BT ofrece un sonido natural, con una gran claridad y precisión, que se dispersa de manera uniforme. Un parlante que asegura potencia y calidad por igual en la reproducción de contenidos multimedia. Versátil y funcional. Disfrutar de todos los sonidos- graves, medios y agudos- con alta fidelidad y una excelente calidad es posible con este parlante de tipo woofer, subwoofer, tweeter, incluso cuando subas el volumen. Olvidate del amplificador. Al ser activo solo necesitarás conectarlo a la fuente de sonido y el mismo equipo se encargará de amplificar y reproducir: ganarás practicidad y espacio, ya que además requiere menos cableado que uno pasivo. Es la solución más conveniente si querés producir música en tu casa o en un estudio, y también para DJs.",
    category: "audio",
    codigo: 3641,
  },
  {
    id: 274,
    img: 1538,
    title: "parlante termuki kanji sp-kja870a-dj  ",
    price: "$00,00",
    detail:
      "Descripción: parlante termuki kanji ofrece un sonido natural, con una gran claridad y precisión, que se dispersa de manera uniforme. Un parlante que asegura potencia y calidad por igual en la reproducción de contenidos multimedia. Versátil y funcional. Disfrutar de un amplio espectro de sonidos, incluso los más agudos es posible con este parlante woofer, tweeter. Vas a sentir la diferencia en la calidad sonora excelente. Olvidate del amplificador. Al ser activo solo necesitarás conectarlo a la fuente de sonido y el mismo equipo se encargará de amplificar y reproducir: ganarás practicidad y espacio, ya que además requiere menos cableado que uno pasivo. Es la solución más conveniente si querés producir música en tu casa o en un estudio, y también para DJs.",
    category: "audio",
    codigo: 1538,
  },
  {
    id: 275,
    img: 3707,
    title: "parlante crown mustang negro bluetooth djs-1002bt  ",
    price: "$00,00",
    detail:
      "Descripción: Crown Mustang DJS-1002BT ofrece un sonido natural, con una gran claridad y precisión, que se dispersa de manera uniforme. Un parlante que asegura potencia y calidad por igual en la reproducción de contenidos multimedia. Versátil y funcional. Disfrutar de un amplio espectro de sonidos, incluso los más agudos es posible con este parlante woofer, tweeter. Vas a sentir la diferencia en la calidad sonora excelente. Olvidate del amplificador. Al ser activo solo necesitarás conectarlo a la fuente de sonido y el mismo equipo se encargará de amplificar y reproducir: ganarás practicidad y espacio, ya que además requiere menos cableado que uno pasivo. Es la solución más conveniente si querés producir música en tu casa o en un estudio, y también para DJs.",
    category: "audio",
    codigo: 3707,
  },
  {
    id: 276,
    img: 3096,
    title: "monitor lg lcd 29´ 29wp500-b wide  ",
    price: "$00,00",
    detail:
      "Descripción: LG busca entender a los usuarios para ofrecerles óptimas soluciones y nuevas experiencias a través de la evolución tecnológica. Disfrutá de la perfecta combinación de diseño, calidad y rendimiento que la empresa te ofrece en este monitor. Un monitor a tu medida. Gracias a su pantalla LCD vas a obtener gráficas con gran nitidez, colores vivos y atractivos. Una experiencia visual de calidad. Este monitor de 29´ te va a resultar cómodo para estudiar, trabajar o ver una película en tus tiempos de ocio. Asimismo, su resolución de 2560 x 1080 te permite disfrutar de momentos únicos gracias a una imagen de alta fidelidad. Una de sus virtudes es que posee pantalla antirreflejo, de esta manera no verás reflejado lo que está detrás de vos y vas a evitar forzar tu vista para enfocar el contenido. Su tiempo de respuesta de 5 ms lo hace ideal para gamers y cinéfilos porque es capaz de mostrar imágenes en movimiento sin halos o bordes borrosos.",
    category: "monitores",
    codigo: 3096,
  },
  {
    id: 277,
    img: 3095,
    title: "monitor lg led 27´ 27mk400h-b hdmi  ",
    price: "$00,00",
    detail:
      "Descripción: LG busca entender a los usuarios para ofrecerles óptimas soluciones y nuevas experiencias a través de la evolución tecnológica. Disfrutá de la perfecta combinación de diseño, calidad y rendimiento que la empresa te ofrece en este monitor. Un monitor a tu medida. Con tu pantalla LED no solo ahorrás energía, ya que su consumo es bajo, sino que vas a ver colores nítidos y definidos en tus películas o series favoritas. Una experiencia visual de calidad. Este monitor de 27´ te va a resultar cómodo para estudiar, trabajar o ver una película en tus tiempos de ocio. Asimismo, su resolución de 1920 x 1080 te permite disfrutar de momentos únicos gracias a una imagen de alta fidelidad. Una de sus virtudes es que posee pantalla antirreflejo, de esta manera no verás reflejado lo que está detrás de vos y vas a evitar forzar tu vista para enfocar el contenido. Su tiempo de respuesta de 2 ms lo hace ideal para gamers y cinéfilos porque es capaz de mostrar imágenes en movimiento sin halos o bordes borrosos.",
    category: "monitores",
    codigo: 3095,
  },
  {
    id: 278,
    img: 3094,
    title: "monitor lg led 19´ 19m38a-b  ",
    price: "$00,00",
    detail:
      "Descripción: LG busca entender a los usuarios para ofrecerles óptimas soluciones y nuevas experiencias a través de la evolución tecnológica. Disfrutá de la perfecta combinación de diseño, calidad y rendimiento que la empresa te ofrece en este monitor. Un monitor a tu medida. Con tu pantalla LED no solo ahorrás energía, ya que su consumo es bajo, sino que vas a ver colores nítidos y definidos en tus películas o series favoritas. Una experiencia visual de calidad. Sus 19´ te van a resultar ideales en tu vida diaria, ya sea para estudiar o trabajar. Asimismo, su resolución de 1366 x 768 te permite disfrutar de momentos únicos gracias a una imagen de alta fidelidad. Una de sus virtudes es que posee pantalla antirreflejo, de esta manera no verás reflejado lo que está detrás de vos y vas a evitar forzar tu vista para enfocar el contenido.",
    category: "monitores",
    codigo: 3094,
  },
  {
    id: 279,
    img: 512,
    title: "tv monitor kanji 24  ",
    price: "$00,00",
    detail:
      "Descripción: Con el TV KJ-24TM005 vas a poder disfrutar de tus contenidos favoritos como películas y programas de interés, con gran calidad y desde la comodidad de tu sillón. Sumergite en la pantalla. Su resolución Full HD muestra una clara evolución frente a su antecesora. Las imágenes que vas a ver van a tener una calidad superior con un alto nivel de detalle y colores mucho más llamativos.",
    category: "monitores",
    codigo: 512,
  },
];


export default function getItems() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(data);
    }, 2000);
  });
}

export function getItemsSingle(idItem) {
  return new Promise((resolve, reject) => {
    let itemFind = data.find((item) => {
      return item.id === parseInt(idItem);
    });

    setTimeout(() => {
      if (itemFind) resolve(itemFind);
      else reject(new Error("Item no encontrado"));
    }, 2000);
  });
}

export function getItemsByCategory(cat) {
  return new Promise((resolve, reject) => {
    let itemFind = data.filter((item) => {
      return item.category === cat;
    });

    setTimeout(() => {
      if (itemFind) resolve(itemFind);
      else reject(new Error("Item no encontrado"));
    }, 2000);
  });
}
